blank_issues_enabled: false
contact_links:
  - name: ğŸ“š DocumentaciÃ³n
    url: https://github.com/Sale-ADS/sa-documentation
    about: Revisa la documentaciÃ³n antes de crear un issue
  - name: ğŸ’¬ Discusiones
    url: https://github.com/orgs/Sale-ADS/discussions
    about: Para preguntas o discusiones generales
